### ISSUE TITLE
Feature req: Pandoc Citations

### ISSUE THREAD

**Issue by DanielOberg** [jaspervdj/hakyll-contrib#4]
Support the Pandoc bibliography flag.

**Comment by jaspervdj** [comment]
Could you elaborate on this? What is your specific use case? Do you want to stick with `hakyll-contrib` or are you willing to use `hakyll`? Cheers!

**Comment by DanielOberg** [comment]
In a perfect world I would like something like this:

```
  smallBlogWith defaultSmallBlogConfiguration
    { 
      bibliography = "/var/www/blog/citations.bib"
    }
```

And after that write my blogposts like this:

```
Blah blah [@doe99, pp. 33-35, 38-39 and *passim*].
```

This would help me a lot. It would mean that my master thesis will simply be a concatenation of blogposts. :)

I'm willing to use Hakyll only, but it would mean that I would copy and paste most of the functionality from smallBlogWith.

**Comment by jaspervdj** [comment]
OK, since I figured some people could really benefit from having proper references in Hakyll, I'll implement a `Hakyll.Web.Pandoc.Biblio` module (see jaspervdj/hakyll@d3140f397c2cdf3be193380d1f9bea003817a49e). It turns out to be non-trivial -- I'll post a status update in this issue when I get it working.

**Comment by DanielOberg** [comment]
I really, really appreciate it.

**Comment by jaspervdj** [comment]
I've added a [references example](https://github.com/jaspervdj/hakyll-examples/tree/master/references) to the `hakyll-examples` repo. Note that it requires the git version of Hakyll -- I haven't released the changes on Hackage yet. Does this look like a reasonable API to you?

**Comment by DanielOberg** [comment]
It looks perfect! Thank you!
